### ISSUE TITLE
Updating password fails validation

### ISSUE THREAD

**Issue by BforBen** [RoyalBoroughKingston/ck-backend#32]
**Describe the bug**

The edit user page provides the following guidance on passwords:

> The password must be at least eight characters long, contain one uppercase letter, one lowercase letter, one number and one special character ($@$!%*?&.).

I've tried to update my password to `w(tqq)7DHKTTN*a?Z&QL%iU&n` and it fails the check. This appears to meet the complexity requirements.

ChromeOS v69

**Comment by matthew-inamdar** [comment]
The help text seems to be misleading, the brackets are not valid special characters, but only used to indicate what special characters are used.

Brackets should be added to the valid list of special characters.

**Comment by matthew-inamdar** [comment]
Closing as this is now being tracked on the Trello board
