### ISSUE TITLE
Edit user page

### ISSUE THREAD

**Issue by BforBen** [RoyalBoroughKingston/ck-backend#33]
I am a Global Admin. The Edit User screen is very tall as it appears to list every organisation and service I am an admin for which appears unnecessary.

I have to scroll all the way down the page to find the "Update" button to submit changes.

There is not enough feedback when the Update button is clicked especially if there is an error on the page (as was the case when updating the password). I clicked the Update button, it changed to "Updating..." and then returned to "Update". It wasn't clear if the update was successful or not. It was only scrolling back up the page that I found the password error.

**Comment by matthew-inamdar** [comment]
Agreed, we need some logic which takes into account the hierarchy.

Perhaps we group the permissions by organisation and further by service? A custom component may be needed to be designed which displays this information more efficiently than the current repeating list of every single role the user has.
