### ISSUE TITLE
InvalidCharacterError in /thesuarus/edit

### ISSUE THREAD

**Issue by AyupMike** [RoyalBoroughKingston/ck-backend#60]
## Error in Connected Kingston Backend

**InvalidCharacterError** in **/thesuarus/edit**
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

[View on Bugsnag](https://app.bugsnag.com/ayup-digital/connected-kingston-backend/errors/5c19fd82a98715001975a9a2?event_id=5c1a2f1300320081fe120000&i=gh&m=ci)

## Stacktrace

    src/views/thesaurus/Edit.vue:84 - VueComponent.base64Decode
    src/views/thesaurus/Edit.vue:72 - VueComponent._callee$

[View full stacktrace](https://app.bugsnag.com/ayup-digital/connected-kingston-backend/errors/5c19fd82a98715001975a9a2?event_id=5c1a2f1300320081fe120000&i=gh&m=ci)

*Created by Mike Stephens via Bugsnag*

**Comment by AyupMike** [comment]
Wondering if [this issue](https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings) is related?

**Comment by matthew-inamdar** [comment]
This should be resolved in #70
